site_name: Android Notes
site_url: https://HJHL.github.io/android
site_author: Li Jiahui
site_description: A Android programer's notes
nav:
  - Home: 'index.md'
  - About: 'about.md'
theme:
  name: material
  language: zh